Practice1/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('post/create/', views.CreatePost.as_view(), name='post_create_url'),
    path('<int:id>/', views.post_detail, name='post_detail'),

]

Practice1/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

import account
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls')),
]

Practice1/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset() \
            .filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)

    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Our custom manager.

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title

Practice1/blog/forms.py
from django import forms
from .models import Post
from django.core.exceptions import ValidationError

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'slug', 'author', 'body', 'status']

    def clean_slug(self):
        new_slug = self.cleaned_data['slug'].lower()
        if new_slug == 'create':
            raise ValidationError('Slug may not be "Create" ')
        return new_slug

Practice1/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from django.views.generic import View
from .forms import PostForm

def post_list(request):
    posts = Post.published.all()
    return render(request,
                 'blog/post/list.html',
                 {'posts': posts})


def post_detail(request, id):
    post = get_object_or_404(Post,
                             id=id,
                             status=Post.Status.PUBLISHED)
    return render(request,
                  'blog/post/detail.html',
                  {'post': post})

class CreatePost(View):
    def get(self, request):
        form = PostForm
        return render(request, 'blog/post/create.html',
                {'form': form})

    def post(self, request):
        bound_form = PostForm(request.POST)
        if bound_form.is_valid():
            new_post = bound_form.save()
            return redirect('/blog/')
        return render(request, 'blog/post/create.html',
                      {'form': bound_form})

Practice1/blog/templates/blog/post/create.html
{% extends "blog/base.html" %}

{% block title %}Create Post{% endblock %}

{% block content %}
<div style="display: flex; justify-content: center; align-items: center; flex-direction: column;">
    <h1 style="text-align: center;">Create Post</h1>
    <form class="" method="post" style="width: 50%;">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group" style="margin-bottom: 20px;">
                {% if field.errors %}
                    <div class="alert alert-danger">
                        {{ field.errors }}
                    </div>
                {% endif %}
                <label style="display: block; text-align: left; margin-bottom: 5px; font-weight: bold;">
                    {{ field.label }}
                </label>
                <div style="display: flex; justify-content: space-between;">
                    {{ field }}
                </div>
            </div>
        {% endfor %}
        <div style="text-align: center;">
            <button type="submit" name="button" class="btn btn-primary">Create post</button>
        </div>
    </form>
</div>
{% endblock %}

Practice1/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.body|linebreaks }}
{% endblock %}

Practice1/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}
  <h1>My Blog</h1>
  {% for post in posts %}
    <h2>
      <a href="{% url 'blog:post_detail' post.id %}">
        {{ post.title }}
      </a>
    </h2>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}
{% endblock %}